[pytest]
markers =
  unit: Unit tests
  integration: Integration tests
  e2e: End-to-end tests
  smoke: Smoke tests
addopts = --cov=infra --cov-report=xml:coverage.xml --cov-report=html:coverage_html --cov-report=term-missing
pythonpath = .
